Tech/intr 03/refactoring according to todos
Doomsdhg/internship-project pull request #18
Opened 2022-05-11 13:29 UTC by Doomsdhg

2022-05-13 11:59 UTC, Batsenka requested changes
Fix it all

2022-05-13 11:59 UTC, Batsenka commented on src/app/constants/main.constants.ts
> +import {TranslationsEndpoints} from './translations-endpoints.constants';
move it in this file

2022-05-13 11:59 UTC, Batsenka commented on src/app/constants/main.constants.ts
> +import {TranslationsEndpoints} from './translations-endpoints.constants';
{Themes} - as I see, you didn't start linter - because wrong formatting!

2022-05-13 11:59 UTC, Batsenka commented on src/app/constants/main.constants.ts
> +import {ApiEndpoints} from './api-endpoints.constants';
main.constants.ts - > constants.ts

2022-05-13 11:59 UTC, Batsenka commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly TRANSACTIONS = `${environment.serverUrl}admin/transactions`;
static readonly BASE = ${environment.serverUrl};

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/header/header.component.ts
> +  private setCurrentRoute(): void {
private methods should be placed in bottom of component - under all publics

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/guard-dialog-content/guard-dialog-content.component.ts
> +  public close(decision: boolean): void {
closeDialog

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/guard-dialog-content/guard-dialog-content.component.ts
> +  public close(decision: boolean): void {
np:

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/header/header.component.html
>                  <span class="material-icons">
enableLightTheme(); (NP)

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/header/header.component.ts
> +    const theme = localStorage.getItem(Constants.LOCAL_STORAGE_ACCESSORS.THEME) || Constants.THEMES.LIGHT;
setTheme(?) - not good naming

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/header/header.component.ts
> +  public switchTheme(selectedTheme: string): void {
selectedTheme: ThemeType

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/header/header.component.ts
> +  private setCurrentRoute(): void {
throught all application

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/select-language/select-language.component.ts
> +  private language!: string | null;
language ?

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/transactions-table/transactions-table.component.ts
> -export interface Column {
should pleces in the same component/page ( all application)

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/components/transactions-table/transactions-table.component.ts
> +  public displayedColumns: string[] = [
to local constants in your component level

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/interceptors/auth.interceptor.ts
> +    if (request.url !== `${environment.serverUrl}${Constants.API_ENDPOINTS.LOGIN}`) {
`${environment.serverUrl}${Constants.API_ENDPOINTS.LOGIN} - request.url !== ApiEdpoints.LOGIN

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/pages/transactions-table-page/transactions-table-page.component.ts
>    styleUrls: []
remove empty styles

2022-05-13 11:59 UTC, Batsenka commented on src/app/modules/pages/transactions-table-page/transactions-table-page.component.ts
> +  @ViewChild(TransactionsTableComponent) transactionsTableComponent!: TransactionsTableComponent;
insert empty line

2022-05-13 11:59 UTC, Batsenka commented on src/app/services/web-services/transaction-api.service.ts
> +    return this.http.delete(`${Constants.API_ENDPOINTS.TRANSACTIONS}${id}`);
extend BaseApiService

2022-05-13 11:59 UTC, Batsenka commented on src/app/services/web-services/transaction-api.service.ts
> +  public confirmTransaction(externalId: string | undefined, provider: string | undefined): Observable<Transaction[]> {
undefined for apiService?

2022-05-13 11:59 UTC, Batsenka commented on src/app/services/web-services/transaction-api.service.ts
> +    return this.http.post(`${Constants.API_ENDPOINTS.TRANSACTIONS}?external_id=${externalId}&provider=${provider}`,
...post(ApiEndpoins.createNewTransaction(String externalId, String provide) -> ApiEndpoins.createNewTransaction(externalId, provider)

2022-05-17 16:16 UTC, Batsenka requested changes

2022-05-18 08:24 UTC, Doomsdhg commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly TRANSACTIONS = `${this.BASE_URL || this.PRODUCTION_BASE_URL}admin/transactions`;
'admin/transactions' url doesnt response with all transactions

2022-05-18 08:25 UTC, Doomsdhg commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly TRANSACTIONS = `${this.BASE_URL || this.PRODUCTION_BASE_URL}admin/transactions`;
> TRANSACTIONS - not correct; getAllTransactions looking better

'admin/transactions' url doesnt response with all transactions

2022-05-18 08:27 UTC, Doomsdhg commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly getConfirmationUrl =
?

2022-05-18 08:28 UTC, Doomsdhg commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly getDeletionUrl = (id: string): string =>  `${ApiEndpoints.TRANSACTIONS}${id}`;
extra line?

2022-05-18 09:29 UTC, Batsenka commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly getDeletionUrl = (id: string): string =>  `${ApiEndpoints.TRANSACTIONS}${id}`;
=>  `

2022-05-18 09:39 UTC, Doomsdhg commented on src/app/constants/api-endpoints.constants.ts
> +    static readonly getDeletionUrl = (id: string): string =>  `${ApiEndpoints.TRANSACTIONS}${id}`;
> 

its required by lint

2022-05-18 15:27 UTC, Batsenka approved these changes
Fix before merge

2022-05-18 15:27 UTC, Batsenka commented on src/app/modules/directives/numbers-limit.directive.ts
> +// This directive limits the size of number you can type in input.
add empty lines after and befire your description

2022-05-18 15:46 UTC, merged